### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by antonioribeiro** [JayBizzle/Laravel-Crawler-Detect#1]
Your package looks nice, any chances of a stable version anytime soon?

I would like to use it on https://github.com/antonioribeiro/tracker.

Thank you!

**Comment by JayBizzle** [comment]
Yeah, I'll get a 0.1 release prepped the next couple of hours.

I was hoping to do a bit more research on Crawler agents, but I have a set of test data containing about 4 million rows that seems to work pretty well so i think it is a good starting point.

Definitely open to pull requests if you find any bots not detected with this library.

I'll update when I've pushed a release.

**Comment by antonioribeiro** [comment]
As far as I can tell, there's no other list of bots as complete as yours around. You should decouple your class from Laravel, creating a second package for your PHP class only, so the whole PHP ecossystem can benefit from your class.

Very nice, thank you!

**Comment by JayBizzle** [comment]
Yeah, i agree about the decoupling. I'm going to start this now, then make a release once that is complete :+1:

**Comment by JayBizzle** [comment]
All done.

New library repo here https://github.com/JayBizzle/Crawler-Detect (jus the basics for now, will add tests and a README later)

`composer require jaybizzle/laravel-crawler-detect 1.*`

Thanks for the ideas!

\cc @antonioribeiro

**Comment by antonioribeiro** [comment]
Great! Thank you!
