### ISSUE TITLE
Undefined type 'Crawler'.

### ISSUE THREAD

**Issue by Zephni** [JayBizzle/Laravel-Crawler-Detect#18]
On a fresh Laravel 8x install I followed the steps in the README like so:

Added " Jaybizzle\LaravelCrawlerDetect\LaravelCrawlerDetectServiceProvider::class," to config.app

Added " 'Crawler'   => Jaybizzle\LaravelCrawlerDetect\Facades\LaravelCrawlerDetect::class," to aliases in config.app

Added "use Crawler;" at the top of a Livewire component

But when trying to use "Crawler::isCrawler()" I am getting the error: "Undefined type 'Crawler'."

Is there something I am missing?

**Comment by JayBizzle** [comment]
Looks okay to me.

Your going to have to give me more information before I can help you further
